class_name SourceSurfaces extends Node

static var sounds:Dictionary = {
	"body":
		{
		"break" =
			[
				preload("res://sounds/hl2/physics/body/body_medium_break2.wav"),
				preload("res://sounds/hl2/physics/body/body_medium_break3.wav"),
				preload("res://sounds/hl2/physics/body/body_medium_break4.wav"),
			],
		"impact" =
			{
			"soft" =
				[
					preload("res://sounds/hl2/physics/body/body_medium_impact_soft1.wav"),
					preload("res://sounds/hl2/physics/body/body_medium_impact_soft2.wav"),
					preload("res://sounds/hl2/physics/body/body_medium_impact_soft3.wav"),
					preload("res://sounds/hl2/physics/body/body_medium_impact_soft4.wav"),
					preload("res://sounds/hl2/physics/body/body_medium_impact_soft5.wav"),
					preload("res://sounds/hl2/physics/body/body_medium_impact_soft6.wav"),
					preload("res://sounds/hl2/physics/body/body_medium_impact_soft7.wav"),
				]
			},
		"scrape" =
			{
			"rough" = [preload("res://sounds/hl2/physics/body/body_medium_scrape_rough_loop1.wav")],
			"smooth" = [preload("res://sounds/hl2/physics/body/body_medium_scrape_smooth_loop1.wav")]
			},
		},
	

	"metal_barrel":
				{
					"impact":
						{
							"hard":
								[
									preload("res://sounds/hl2/physics/metal/metal_barrel_impact_hard1.wav"),
									preload("res://sounds/hl2/physics/metal/metal_barrel_impact_hard2.wav"),
									preload("res://sounds/hl2/physics/metal/metal_barrel_impact_hard3.wav"),
									preload("res://sounds/hl2/physics/metal/metal_barrel_impact_hard5.wav"),
									preload("res://sounds/hl2/physics/metal/metal_barrel_impact_hard6.wav"),
									preload("res://sounds/hl2/physics/metal/metal_barrel_impact_hard7.wav"),
								],
							"soft":
								[
									preload("res://sounds/hl2/physics/metal/metal_barrel_impact_soft1.wav"),
									preload("res://sounds/hl2/physics/metal/metal_barrel_impact_soft2.wav"),
									preload("res://sounds/hl2/physics/metal/metal_barrel_impact_soft3.wav"),
									preload("res://sounds/hl2/physics/metal/metal_barrel_impact_soft4.wav"),
								]
						}
				},
	"metal_box":
				{
					"break":
							[
								preload("res://sounds/hl2/physics/metal/metal_box_break1.wav"),
								preload("res://sounds/hl2/physics/metal/metal_box_break2.wav"),
							],
					"impact":
						{
							"bullet":
									[
										preload("res://sounds/hl2/physics/metal/metal_box_impact_bullet1.wav"),
										preload("res://sounds/hl2/physics/metal/metal_box_impact_bullet2.wav"),
										preload("res://sounds/hl2/physics/metal/metal_box_impact_bullet3.wav"),
									],
							"hard":
									[
										preload("res://sounds/hl2/physics/metal/metal_box_impact_hard1.wav"),
										preload("res://sounds/hl2/physics/metal/metal_box_impact_hard2.wav"),
										preload("res://sounds/hl2/physics/metal/metal_box_impact_hard3.wav"),
									],
							"soft":
									[
										preload("res://sounds/hl2/physics/metal/metal_box_impact_soft1.wav"),
										preload("res://sounds/hl2/physics/metal/metal_box_impact_soft2.wav"),
										preload("res://sounds/hl2/physics/metal/metal_box_impact_soft3.wav"),
									],
						},
					"scrape":
							{
								"rough":
										[
											preload("res://sounds/hl2/physics/metal/metal_box_scrape_rough_loop1.wav"),
											preload("res://sounds/hl2/physics/metal/metal_box_scrape_rough_loop2.wav"),
										],
								"smooth":
										[
											preload("res://sounds/hl2/physics/metal/metal_box_scrape_smooth_loop1.wav"),
										],
							},
					"strain":
							[
								preload("res://sounds/hl2/physics/metal/metal_box_strain1.wav"),
								preload("res://sounds/hl2/physics/metal/metal_box_strain2.wav"),
								preload("res://sounds/hl2/physics/metal/metal_box_strain3.wav"),
								preload("res://sounds/hl2/physics/metal/metal_box_strain4.wav"),
							],
				},
	"metal_canister":
					{
					"scrape":
							{
								"rough":
										[
											preload("res://sounds/hl2/physics/metal/canister_scrape_rough_loop1.wav"),
										],
								"smooth":
										[
											preload("res://sounds/hl2/physics/metal/canister_scrape_smooth_loop1.wav"),
										],
							},
					"impact":
							{
							"hard":
									[
										preload("res://sounds/hl2/physics/metal/metal_canister_impact_hard1.wav"),
										preload("res://sounds/hl2/physics/metal/metal_canister_impact_hard2.wav"),
										preload("res://sounds/hl2/physics/metal/metal_canister_impact_hard3.wav"),
									],
							"soft":
									[
										preload("res://sounds/hl2/physics/metal/metal_canister_impact_soft1.wav"),
										preload("res://sounds/hl2/physics/metal/metal_canister_impact_soft2.wav"),
										preload("res://sounds/hl2/physics/metal/metal_canister_impact_soft3.wav"),
									]
							}
					},

	"flesh":
			{
				"impact":
						{
							"bullet":
									[
										preload("res://sounds/hl2/physics/flesh/flesh_impact_bullet1.wav"),
										preload("res://sounds/hl2/physics/flesh/flesh_impact_bullet2.wav"),
										preload("res://sounds/hl2/physics/flesh/flesh_impact_bullet3.wav"),
										preload("res://sounds/hl2/physics/flesh/flesh_impact_bullet4.wav"),
										preload("res://sounds/hl2/physics/flesh/flesh_impact_bullet5.wav"),
									],
						},
			},

	"concrete":
			{
				"scrape":
						{
						"smooth":
								[
									preload("res://sounds/hl2/physics/concrete/concrete_scrape_smooth_loop1.wav"),
								],
						},
				"impact":
						{
							"soft":
									[
										preload("res://sounds/hl2/physics/concrete/concrete_impact_soft1.wav"),
										preload("res://sounds/hl2/physics/concrete/concrete_impact_soft2.wav"),
										preload("res://sounds/hl2/physics/concrete/concrete_impact_soft3.wav"),
									],
							"hard":
									[
										preload("res://sounds/hl2/physics/concrete/concrete_impact_hard1.wav"),
										preload("res://sounds/hl2/physics/concrete/concrete_impact_hard2.wav"),
										preload("res://sounds/hl2/physics/concrete/concrete_impact_hard3.wav"),
									],
							"bullet":
									[
										preload("res://sounds/hl2/physics/concrete/concrete_impact_bullet1.wav"),
										preload("res://sounds/hl2/physics/concrete/concrete_impact_bullet2.wav"),
										preload("res://sounds/hl2/physics/concrete/concrete_impact_bullet3.wav"),
										preload("res://sounds/hl2/physics/concrete/concrete_impact_bullet4.wav"),
									],
						},
				"break":
						[
							preload("res://sounds/hl2/physics/concrete/concrete_break2.wav"),
							preload("res://sounds/hl2/physics/concrete/concrete_break3.wav"),
						]
			},

	"concrete_boulder":
			{
				"impact":
						{
							"hard":
									[
										preload("res://sounds/hl2/physics/concrete/boulder_impact_hard1.wav"),
										preload("res://sounds/hl2/physics/concrete/boulder_impact_hard2.wav"),
										preload("res://sounds/hl2/physics/concrete/boulder_impact_hard3.wav"),
										preload("res://sounds/hl2/physics/concrete/boulder_impact_hard4.wav"),
									]
						}
			},

	"concrete_block":
			{
				"scrape":
						{
							"rough":
									[
										preload("res://sounds/hl2/physics/concrete/concrete_block_scrape_rough_loop1.wav"),
									]
						},
				"impact":
						{
							"hard":
									[
										preload("res://sounds/hl2/physics/concrete/concrete_block_impact_hard1.wav"),
										preload("res://sounds/hl2/physics/concrete/concrete_block_impact_hard2.wav"),
										preload("res://sounds/hl2/physics/concrete/concrete_block_impact_hard3.wav"),
									]
						}
			}

}
